package gr.teicrete.ie.oop2.arxp.mvc.views;

import gr.teicrete.ie.oop2.arxp.mvc.SingleSelectionController;
import gr.teicrete.ie.oop2.arxp.mvc.SingleSelectionView;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author PK5
 */
public class ComboBoxView extends javax.swing.JFrame implements SingleSelectionView, ActionListener {
    private SingleSelectionController singleSelectionController;
    
    /**
     * Creates new form ComboBoxView
     */
    public ComboBoxView(SingleSelectionController singleSelectionController) {
        this.singleSelectionController = singleSelectionController;
        initComponents();
        for (int i = 0; i <singleSelectionController.getInitialModelValues().length; i++) {
            jComboBox1.addItem(singleSelectionController.getInitialModelValues()[i]);
        }
        jComboBox1.setSelectedIndex(singleSelectionController.getSelectedIndex());
        
        jComboBox1.addActionListener(this);
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getContentPane().add(jComboBox1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void selectionChangedAction(int index) {
        jComboBox1.setSelectedIndex(index);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        singleSelectionController.setSelectedIndex(this, jComboBox1.getSelectedIndex());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables

}
