package gr.teicrete.ie.oop2.arxp.mvc.views;

import gr.teicrete.ie.oop2.arxp.mvc.SingleSelectionController;
import gr.teicrete.ie.oop2.arxp.mvc.SingleSelectionView;

/**
 *
 * @author PK5
 */
public class TextView extends javax.swing.JFrame implements SingleSelectionView {
    private SingleSelectionController singleSelectionController;
    
    /**
     * Creates new form TextView
     */
    public TextView(SingleSelectionController singleSelectionController) {
        this.singleSelectionController = singleSelectionController;
        initComponents();
        jLabel1.setText("The selected index is: "+singleSelectionController.getInitialModelValues()[singleSelectionController.getSelectedIndex()]);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void selectionChangedAction(int index) {
        jLabel1.setText("The selected index is: "+singleSelectionController.getInitialModelValues()[index]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
