package gr.teicrete.ie.oop2.arxp.mvc.views;

import gr.teicrete.ie.oop2.arxp.mvc.SingleSelectionController;
import gr.teicrete.ie.oop2.arxp.mvc.SingleSelectionView;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

/**
 *
 * @author PK5
 */
public class RadioGroupView extends javax.swing.JFrame implements SingleSelectionView, ItemListener {

    private SingleSelectionController singleSelectionController;
    private ButtonGroup group ;

    /**
     * Creates new form RadioGroupView
     */
    public RadioGroupView(SingleSelectionController singleSelectionController) {
        this.singleSelectionController = singleSelectionController;
        initComponents();
        //Group the radio buttons.
        group = new ButtonGroup();
        for (int i = 0; i < singleSelectionController.getInitialModelValues().length; i++) {
            JRadioButton jRadioButton = new JRadioButton(singleSelectionController.getInitialModelValues()[i]);
            group.add(jRadioButton);
            jRadioButton.setSelected(singleSelectionController.getSelectedIndex() == i);
            
            jRadioButton.addItemListener(this);
                        
            add(jRadioButton);
        }
//        ((JRadioButton)getContentPane().getComponent(singleSelectionController.getSelectedIndex()-1)).setSelected(true);
        
        ((GridLayout) getContentPane().getLayout()).setRows(singleSelectionController.getInitialModelValues().length);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void selectionChangedAction(int index) {
       ((JRadioButton)getContentPane().getComponent(index)).setSelected(true);
    }

    @Override
    public void itemStateChanged(ItemEvent ie) {
        if( ((JRadioButton)ie.getItemSelectable()).isSelected() ){
            int selectedIndex;
            for (int i = 0; i < getContentPane().getComponentCount(); i++) {
                if(((JRadioButton)getContentPane().getComponent(i))== (JRadioButton)ie.getItemSelectable()){
                    selectedIndex = i;
                    singleSelectionController.setSelectedIndex(this, selectedIndex);
                    break;
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
